error occurred for using 'TensorFlow 2 Classification Model Zoo' because SavedModel file does not exist.
----------
  File "/usr/local/lib/python3.8/dist-packages/tensorflow/python/saved_model/loader_impl.py", line 111, in parse_saved_model
    raise IOError("SavedModel file does not exist at: %s/{%s|%s}" %
OSError: SavedModel file does not exist at: /tmp/resnet50_v1/{saved_model.pbtxt|saved_model.pb}
----------